### PR TITLE
Add ical feed output

### PR DESCRIPTION
**Pull request by xesxen**
This allows for calenders applications, for ex. Nextcloud instances, to track prior/current/future events as well

### CODE REVIEW

**Comment by xesxen** [comment]
Minor request as well to not pave over prior events from this point on since people might want to look back in this feed

**Comment by sigio** [comment]
I'll have to test if we have the required software on the system before merging this....

**Comment by sigio** [comment]
Had to install python3-icalendar ... but then it worked... so will merge it

**Comment by sigio** [comment]
> Minor request as well to not pave over prior events from this point on since people might want to look back in this feed

Don't particularly like this.... old events will be removed... if people want history, they can clone the github repo and browse in there.

**Pull request merged**
